hacks to build on Debian bookworm (#473)
* psutil/linux.c: remove #include <sys/sysctl.h>

on bookwork sys/sysctl.h is not necssary

to reproduce:
To reproduce the error on Raspberry Pi 4, bookworm
uname -a
Linux raspberrypi 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux
cat /etc/debian_version
12.8

mkdir build
cd  build
cmake .. -DCMAKE_C_FLAGS="-fcommon"
make

[  1%] Building C object CMakeFiles/pilight.dir/libs/pilight/psutil/linux.c.o
/home/a/git/pilight/libs/pilight/psutil/linux.c:5:10: fatal error: sys/sysctl.h: No such file or directory
    5 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pilight.dir/build.make:1128: CMakeFiles/pilight.dir/libs/pilight/psutil/linux.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:573: CMakeFiles/pilight.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

* hack to stop duplicate errors to build on Debian bookworm

This is temp fix.The c code need to solve the duplicate errros.

eventually we should compile with  the default i.e.  -fno-common

rm -fr build # clean any previous builds if there are.
mkdir build
cd  build
cmake -DCMAKE_C_FLAGS=-fcommon ..
make

also I installed avrdudes from source. I thought this necessary
May be not. https://github.com/avrdudes/avrdude.git

====
before this fix:
To reproduce the error on Raspberry Pi 4, bookworm
uname -a
Linux raspberrypi 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux
cat /etc/debian_version
12.8

rm -fr build
mkdir build
cd  build
cmake ..
make  VERBOSE=1

Linking C shared library libpilight.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/pilight_shared.dir/link.txt --verbose=1
/usr/bin/cc -fPIC  -Wall -O3 -DNDEBUG -Wl,-E
...

/io/file.c.o CMakeFiles/pilight.dir/libs/pilight/lua_c/io/serial.c.o CMakeFiles/pilight.dir/libs/pilight/lua_c/io/spi.c.o  -lm -lrt -ldl -lwir
ingx -lmbedtls -lmbedcrypto -lmbedx509 -llua5.1 -lpcap
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x14): multiple definition of `pilight_t'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x8c): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x34): multiple definition of `ssl_server_conf'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0xac): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x11c): multiple definition of `ssl_client_conf'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x194): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x204): multiple definition of `ssl_cache'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x27c): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x22c): multiple definition of `ssl_server_crt'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x2a4): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x384): multiple definition of `ssl_pk_key'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x3fc): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x38c): multiple definition of `ssl_ctr_drbg'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x404): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x4e8): multiple definition of `ssl_entropy'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x560): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x9788): multiple definition of `event_action_args_t'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x9800): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x9798): multiple definition of `threadqueue_t'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x9810): first defined here
/usr/bin/ld: CMakeFiles/pilight.dir/libs/avrdude/avr.c.o:(.bss+0x97f8): multiple definition of `uv_custom_poll_t'; CMakeFiles/pilight.dir/libs/libuv/threadpool.c.o:(.bss+0x9870): first defined here
...
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pilight_shared.dir/build.make:530: libpilight.so] Error 1
make[2]: Leaving directory '/home/a/git/pilight/build'